### ISSUE TITLE
App crashing sometimes after requesting files

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-ios#133]
Sometimes, my app just crashes on some random screen, after the data was requested earlier (possibly some listeners are removed for incoming data in the meantime).

This is how stacktrace of a crash looks like
![image](https://user-images.githubusercontent.com/6838180/66670895-2b0d9400-ec5b-11e9-8133-06d41333ab3a.png)

Seems like L457 is causing crash

I've only tried it in the Simulator so far tho

**Comment by harunsmrkovic** [comment]
I got this again, I think that reproduction instruction could be to try calling getSessionData multiple times...

**Comment by brokenzz** [comment]
Hi Harun,

Could you please provide the crash message / exception?

You also mention 

> re-initalization of JS code seems to trigger it sometimes

The SDK does not contain any JS code - please clarify what you are referring to? :)

**Comment by harunsmrkovic** [comment]
Did not have this happen any more
