### ISSUE TITLE
Receiving 404 on Get Accounts call

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-ios#143]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-ios/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://digime.github.io/digime-sdk-ios/index.html) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894) 
- [x] This issue does not relate to security and can be disclosed publicly on Github. 
## Environment
Describe your development environment here. Please provide as much information as you can, noting the following details if possible:
- Xcode Version: `11.1`
- Swift Version: N/A (if applicable)
- Installation Platform & Version: `[Cocoapods]` version `3.0.1#ubdi/interim-scoping`
## Goals
I want to receive a list of accounts user has
## Expected Results
I get the list
## Actual Results
I don't get the list - I get 404 instead

```
[tid:com.facebook.react.JavaScript] '[digi.me] Get Accounts failed', [Error: The operation couldn't be completed. (me.digi.sdk.api error 404.)]
```

My expectation is that the API would return 404 only as a real error, and otherwise wait for the list to appear if the reason for its' not-appearing is known/expected.

## Steps to Reproduce
Not sure, but @olileung suggested that it could be due to premature call to this fn (API not waiting for accounts to be ready).

## Code Samples & Details
N/A

**Comment by BeckFW** [comment]
Currently this behaviour from the backend is expected. The iOS SDK has been built to handle the 404 errors and retry 5 times by default.
