### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-ios#189]
## Checklist
- [x] I’m using the latest version of the digi.me Private Sharing SDK.
- [x] I'm using the latest version of the digi.me App.
- [x] I've searched for existing [GitHub issues](https://github.com/digime/digime-sdk-ios/issues)
- [x] I've looked for existing answers in the [SDK Documentation](https://digime.github.io/digime-sdk-ios/index.html) and [Developer FAQs](https://digime.freshdesk.com/support/solutions/9000115894) 
- [x] This issue does not relate to security and can be disclosed publicly on Github. 
## Environment
Describe your development environment here. Please provide as much information as you can, noting the following details if possible:
- Xcode Version: `X.X.X`
- Swift Version: `X.X.X` (if applicable)
- Installation Platform & Version: `[Cocoapods, Manual]` version `X.X.X`
## Goals
What are you trying to achieve? 
## Expected Results
What do you expect to happen?
## Actual Results
What actually happened?
## Steps to Reproduce
What are the steps necessary to reproduce this issue?
## Code Samples & Details

https://sentry.io/share/issue/996215751fda4d06849357e1be782889/

**Comment by michaeleustace** [comment]
SDK has been rewritten, so this no longer holds.
